FROM python:3.13-slim

WORKDIR /app

RUN pip install uv

ENV UV_SYSTEM_PYTHON=1

COPY pyproject.toml .

RUN uv pip install -r pyproject.toml

COPY app/ ./app/
COPY alembic/ ./alembic/
COPY alembic.ini .

EXPOSE 8000

CMD ["sh", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 2"]
